#pragma once

#define MATRIX_UNSELECT_DRIVE_HIGH
#define CORTEX_ENABLE_WFI_IDLE FALSE

#define EARLY_INIT_PERFORM_BOOTLOADER_JUMP TRUE

#define DEBOUNCE 5

#ifndef NOP_FUDGE
#    define NOP_FUDGE 0.4
#endif

#define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 1151
#define EEPROM_SIZE 1152
#define FEE_PAGE_SIZE (0x200)
#define FEE_PAGE_COUNT (8)
#define FEE_PAGE_BASE_ADDRESS (0x1F000)
#define FEE_MCU_FLASH_SIZE (0x1000)
#define EECONFIG_USER_DATA_SIZE 4
#define EECONFIG_KB_DATA_SIZE 1
#define TRANSIENT_EEPROM_SIZE 4096

// BLE configuration for LUMA40
#define USER_BLE_ID (0X00A5) // LUMA40 BLE ID
#define USER_BLE1_NAME "LUMA40-1"
#define USER_BLE2_NAME "LUMA40-2"
#define USER_BLE3_NAME "LUMA40-3"

// LED Index Definitions for keyboard_common library
#define LED_CONNECTION_INDEX 11 // Connection type indicator (BLE/2.4G/USB)
#define LED_CAP_INDEX 12        // Caps Lock indicator
#define LED_BATT_INDEX 36       // Battery status indicator
#define LED_WIN_L_INDEX 40      // Win Lock indicator
#define LED_BLE_1_INDEX 1       // 'Q' key position
#define LED_BLE_2_INDEX 2       // 'W' key position
#define LED_BLE_3_INDEX 3       // 'E' key position
#define LED_2P4G_INDEX 4        // 'R' key position
#define LED_USB_INDEX 5         // 'T' key position

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define DYNAMIC_KEYMAP_MACRO_COUNT 16

// MOUSEKEY
#define MOUSEKEY_DELAY 8
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_INITIAL_SPEED 1
#define MOUSEKEY_MAX_SPEED 24
#define MOUSEKEY_TIME_TO_MAX 48
#define MOUSEKEY_WHEEL_DELAY 8
#define MOUSEKEY_WHEEL_INTERVAL 64
#define MOUSEKEY_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_INITIAL_SPEED 1
#define MOUSEKEY_WHEEL_MAX_SPEED 16
#define MOUSEKEY_WHEEL_TIME_TO_MAX 128

#define TAPPING_TERM 170
#define HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define COMBO_TERM 40
#define TAP_CODE_DELAY 10

// RGB Matrix

// LED
#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_KEYPRESSES
    #define RGB_MATRIX_KEYRELEASES
    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    #define RGB_DISABLE_AFTER_TIMEOUT 0
    #define RGB_MATRIX_LED_FLUSH_LIMIT 16
    #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
    #define RGB_MATRIX_SLEEP
    #define RGB_MATRIX_LED_COUNT 47
    #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
    #define RGB_MATRIX_STARTUP_HUE 128
    #define RGB_MATRIX_STARTUP_SAT 255
    #define RGB_MATRIX_STARTUP_VAL 128
    
    // エフェクト選択 (不要なものは #undef する)
    #define ENABLE_RGB_MATRIX_ALPHAS_MODS
    #define ENABLE_RGB_MATRIX_BREATHING
    #define ENABLE_RGB_MATRIX_CYCLE_ALL
    #define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
    #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
    #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
    #define ENABLE_RGB_MATRIX_DUAL_BEACON
    #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
    #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
    #define ENABLE_RGB_MATRIX_RAINDROPS
    #define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
    #define ENABLE_RGB_MATRIX_TYPING_HEATMAP
    #define ENABLE_RGB_MATRIX_DIGITAL_RAIN
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS

    #define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_CROSS
    #define RGB_MATRIX_DEFAULT_VAL  16
    #define RGB_MATRIX_DEFAULT_HUE  128
    #define RGB_MATRIX_DEFAULT_SAT  255
#endif

/* Mechanical locking support. Use KC_LCAP, KC_LNUM or KC_LSCR instead in keymap */
//#define LOCKING_SUPPORT_ENABLE
/* Locking resynchronize hack */
//#define LOCKING_RESYNC_ENABLE

// OVERRIDE
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_F18
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_LEFT_SHIFT) , MOD_BIT(KC_RIGHT_SHIFT) }

// MACRO
#define DYNAMIC_KEYMAP_MACRO_DELAY 4
#define DYNAMIC_KEYMAP_LAYER_COUNT 5